# Our three deployment environments are devs, staff and public
deploy: &deploy
  adapter: postgresql
  port: 5432
  host:     <%= Secrets::DATABASE_HOST %>
  username: <%= Secrets::DATABASE_USERNAME %>
  password: <%= Secrets::DATABASE_PASSWORD %>
  pool: 20

devs:
  <<: *deploy
  database: adacms_devs

staging:
  <<: *deploy
  database: adacms_staging

staff:
  <<: *deploy
  database: adacms_public

public:
  <<: *deploy
  database: adacms_public

nesstar:
  adapter: mysql2
  host:     <%= Secrets::NESSTAR_DATABASE_HOST %>
  username: <%= Secrets::NESSTAR_DATABASE_USERNAME %>
  password: <%= Secrets::NESSTAR_DATABASE_PASSWORD %>
  database: nesstar4
