abstract_text: 
access_conditions:
access_place:
accessibility:
additivity:
addressee:
addressee_copy:
aggregation:
alternative_title:
analytic_unit:
audience:
authorising_statute:
auto_remove_date:
availability:
beginning_date:
bibliographic_citation:
category:
coll_mode:
collection_end:
collection_start:
comment:
concept:
conforms_to:
contributor:
copyright:
coverage:
coverage_temporal_date_capture_period_ends:
created_at:
creation_date:
creator:
current_location:
custodian:
cut_off_date:
d_pa_data_subject_access_exemption:
data_collector:
data_kind:
data_protection_exempt_category:
datafile_id:
date_accepted:
date_acquired:
date_available:
date_available_end:
date_capture_period:
date_closed:
date_copyrighted:
date_created:
date_declared:
date_issued:
date_modified:
date_next_version_due:
date_of_last_review:
date_submitted:
date_valid:
date_valid_end:
dates_modified:
decimal_places:
deploy_language:
descriptor:
digital_signature:
disclosability_to_dpa_data_subject:
disposal:
disposal_action:
disposal_authorised_by:
disposal_comment:
disposal_conditions:
disposal_date:
disposal_export_destination:
disposal_export_status:
disposal_review:
disposal_review_details:
disposal_reviewer_details:
disposal_schedule_id:
disposal_time_period:
distribution_date:
distributor:
doc_alt_titl:
doc_auth_entity:
doc_bibl_cit:
doc_bibl_cit_format:
doc_copyright:
doc_dist_date:
doc_distributor:
doc_eng_title:
doc_lang:
doc_prod_date:
doc_producer:
doc_sub_titl:
doc_title:
e_ir_disclosability_indicator:
e_ir_exemption:
education_level:
end_date:
end_date_of_capture:
end_pos:
eng_abstract:
eng_weight:
expression:
ext_notes_role:
ext_notes_title:
ext_notes_uri:
extent:
external_id:
f_oi_disclosability_indicator:
f_oi_exemption:
f_oi_release_date:
f_oi_release_details:
fileplan_id:
format:
format_schema:
geogr:
geographical_cover:
geographical_unit:
group_access:
has_format:
has_part:
has_version:
home_location:
id:
identifier:
identifier_case_id:
individual_user_access_list:
instructions:
interviewer_instr:
intervl:
is_defined_by:
is_format_of:
is_key:
is_part_of:
is_referenced_by:
is_replaced_by:
is_required_by:
is_version_of:
is_weight:
keyword:
keywords:
label:
language:
last_foi_disclosability_review:
limitations:
location:
mandate:
max_value:
mean_value:
median_value:
mediator:
medium:
method_notes:
min_value:
missing_values:
mode_value:
name:
nation:
nature:
nesstar_id:
no_invalid_responses:
no_responses:
no_valid_responses:
notes:
origin:
original_format:
pdf_file:
period_end:
period_start:
personal_data_aquisition_purpose:
position:
post_question_text:
postcode:
pre_question_text:
preservation:
previous_protective_marking:
process_identifier:
programme:
project:
protective_marking:
protective_marking_change_date:
protective_marking_expiry_date:
provides_definition_of:
publisher:
question_text:
reason_for_redaction:
redaction:
relation:
replaces:
requires:
research_instr:
resource_date:
resource_references:
resource_type:
response:
rights:
sampling:
scale:
schedule_catalog_id:
schedule_date:
schedule_email_text:
sequence_num:
series_id:
series_name:
site:
source:
spatial_location:
spatiality:
start_date_of_capture:
start_pos:
status:
status_of_start_date_of_capture:
std_value:
stdy_alt_titl:
stdy_auth_entity:
stdy_bibl_cit:
stdy_class:
stdy_contact:
stdy_contact_affiliation:
stdy_contact_email:
stdy_contributor:
stdy_copyright:
stdy_data_appraisal:
stdy_data_coll_freq:
stdy_dep_date:
stdy_depositor:
stdy_eng_title:
stdy_id:
stdy_lang:
stdy_par_titl:
stdy_prod_agency:
stdy_prod_date:
stdy_producer:
stdy_producer_abbr:
stdy_status:
stdy_sub_titl:
stdy_version:
stdy_version_date:
stdy_version_notes:
stdy_version_responsibility:
stdy_version_type:
study_id:
sub_resource:
sub_study:
subcat:
subject:
subject_person:
syntax:
system_id:
table_of_contents:
temporal:
time_meth:
time_period:
title:
universe:
updated_at:
updating_frequency:
uri:
val_range_max:
val_range_min:
var_id:
weight:
weighted_mean_value:
weighted_median_value:
weighted_mode_value:
weighted_no_invalid_responses:
weighted_no_valid_responses:
weighted_std_value:
width:
