abstract_text: Abstract
access_conditions: Access Conditions
access_place: Locations of Data Collection
accessibility: 
additivity: 
addressee:
addressee_copy:
aggregation:
alternative_title: Alternative Title
analytic_unit: Unit of Analysis
audience:
authorising_statute:
auto_remove_date:
availability:
beginning_date:
bibliographic_citation: Bibliographic Citation
category:
coll_mode: Mode of Data Collection
collection_end: Start date - Data Collection
collection_start: End date - Data Collection
comment: Comment
concept:
conforms_to:
contributor:
copyright: Copyright
coverage: 
coverage_temporal_date_capture_period_ends:
created_at: Update Creation Date
creation_date: Study Creation Date
creator:
current_location:
custodian:
cut_off_date:
d_pa_data_subject_access_exemption:
data_collector: Data Collectors
data_kind: Data Kind
data_protection_exempt_category:
datafile_id: Data File ID
date_accepted: 
date_acquired:
date_available:
date_available_end:
date_capture_period:
date_closed:
date_copyrighted:
date_created:
date_declared:
date_issued:
date_modified:
date_next_version_due:
date_of_last_review:
date_submitted:
date_valid:
date_valid_end:
dates_modified:
decimal_places: Decimal Places
deploy_language:
descriptor:
digital_signature:
disclosability_to_dpa_data_subject:
disposal:
disposal_action:
disposal_authorised_by:
disposal_comment:
disposal_conditions:
disposal_date:
disposal_export_destination:
disposal_export_status:
disposal_review:
disposal_review_details:
disposal_reviewer_details:
disposal_schedule_id:
disposal_time_period:
distribution_date:
distributor:
doc_alt_titl: Alternative Title (documentation)
doc_auth_entity: Authoring Entity (documentation)
doc_bibl_cit: Bibliographic Citation (documentation)
doc_bibl_cit_format: Bibliographic Citation Format (documentation)
doc_copyright: Copyright (documentation)
doc_dist_date: Distribution Date (documentation)
doc_distributor: Distributor (documentation)
doc_eng_title: Title - English (documentation)
doc_lang: Language (documentation)
doc_prod_date: Production Date (documentation)
doc_producer: Producer (documentation)
doc_sub_titl: Subtitle (documentation)
doc_title: Title (documentation)
e_ir_disclosability_indicator:
e_ir_exemption:
education_level:
end_date:
end_date_of_capture:
end_pos:
eng_abstract:
eng_weight: Weighting
expression:
ext_notes_role:
ext_notes_title:
ext_notes_uri:
extent:
external_id: ADA ID
f_oi_disclosability_indicator:
f_oi_exemption:
f_oi_release_date:
f_oi_release_details:
fileplan_id:
format: Format
format_schema: Format Schema
geogr:
geographical_cover: Geographic Coverage
geographical_unit: Geographic Unit
group_access:
has_format:
has_part:
has_version:
home_location:
id: Variable ID
identifier:
identifier_case_id:
individual_user_access_list:
instructions:
interviewer_instr:
intervl: Interval
is_defined_by:
is_format_of:
is_key:
is_part_of:
is_referenced_by:
is_replaced_by:
is_required_by:
is_version_of:
is_weight:
keyword:
keywords: Keywords
label: Label
language: Language
last_foi_disclosability_review:
limitations:
location:
mandate:
max_value: Maximum
mean_value: Mean
median_value: Median
mediator:
medium:
method_notes: Other Methodology Notes
min_value: Minimum
missing_values: Missing Values
mode_value: Mode
name: Variable Name
nation: Countries
nature:
nesstar_id: Nesstar ID
no_invalid_responses: Invalid Cases
no_responses: Number of Cases
no_valid_responses: Valid Cases
notes:
origin: Original Archive
original_format: Original Format
pdf_file: PDF
period_end: Time Period - Start
period_start: Time Period - End
personal_data_aquisition_purpose:
position: Variable Position
post_question_text: Post-question Text
postcode: Postcode
pre_question_text: Pre-question Text
preservation:
previous_protective_marking:
process_identifier:
programme:
project:
protective_marking:
protective_marking_change_date:
protective_marking_expiry_date:
provides_definition_of:
publisher: Publisher
question_text: Question Text
reason_for_redaction: Reason for Redaction
redaction:
relation:
replaces:
requires:
research_instr: Type of Research Instrument
resource_date:
resource_references:
resource_type:
response: Response Rate
rights:
sampling: Sampling Procedure
scale:
schedule_catalog_id:
schedule_date:
schedule_email_text:
sequence_num:
series_id: Series ID
series_name: Series Name
site:
source:
spatial_location:
spatiality:
start_date_of_capture:
start_pos:
status:
status_of_start_date_of_capture:
std_value: Std. Deviation
stdy_alt_titl: Alternate Title
stdy_auth_entity: Primary Investigator
stdy_bibl_cit: Bibliographic Citation
stdy_class: ADA Processing Level
stdy_contact: Contact
stdy_contact_affiliation: Contact Affiliation
stdy_contact_email: Contact Email
stdy_contributor: Contributor
stdy_copyright: Copyright
stdy_data_appraisal: Other Data Appraisal
stdy_data_coll_freq: Frequency of Data Collection
stdy_dep_date: Deposit Date
stdy_depositor: Depositor
stdy_eng_title: Title - English
stdy_id: ADA ID
stdy_lang: Language
stdy_par_titl: Parallel Title
stdy_prod_agency: Production Agency
stdy_prod_date: Production Date
stdy_producer: Producer
stdy_producer_abbr: Producer abbreviation
stdy_status: ADA Study Level
stdy_sub_titl: Sub-title
stdy_version: Version
stdy_version_date: Version Date
stdy_version_notes: Version Notes
stdy_version_responsibility: Version Responsibility
stdy_version_type: Version Type
study_id: Database Study ID
sub_resource: 
sub_study:
subcat: Topic Classifications
subject:
subject_person:
syntax:
system_id:
table_of_contents:
temporal:
time_meth: Time Method
time_period: Time Period
title: Study Title
universe: Population (Universe)
updated_at: Updated At
updating_frequency:
uri: URI
val_range_max: Maximum
val_range_min: Minimum
var_id: Variable ID
weight: Weighting
weighted_mean_value: Mean (weighted)
weighted_median_value: Median (weighted)
weighted_mode_value: Mode (weighted)
weighted_no_invalid_responses: Invalid Responses (weighted)
weighted_no_valid_responses: Valid Responses (weighted)
weighted_std_value: Std. Dev. (weighted)
width: Variable Width
