development: &development
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
#    path: /Users/nicholas/tmp

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING

production: &production
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING

devs:
  <<: *development

staging:
  <<: *production

staff:
  <<: *production

public:
  <<: *production
