development: &development
  solr:
    hostname: localhost
    port: 8983
    log_level: INFO

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING

production: &production
  solr:
    hostname: web3.mgmt
    port: 8983
    log_level: WARNING

devs:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
staging:
  <<: *production

staff:
  <<: *production

public:
  <<: *production
